### ISSUE TITLE
Fatal error when running composer update

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/plugin_bootstrap#32]
This error just popped up today when doing composer update. I haven't changed any of the files in the vendor folder.

Pretty sure I did a composer update Saturday and did not get this error. I'm not sure this is exactly related to the bootstrap plugin, it could be something to do with composer plugin. I'm also including my composer.json file to help figure this out.

![image](https://cloud.githubusercontent.com/assets/5413608/15511381/e2c7444e-21a0-11e6-8177-33aa129fa319.png)

`{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/qcubed/framework"
    },
    {
      "type": "vcs",
      "url": "https://github.com/qcubed/composer"
    }

  ],
  "name": "qcubed/app-starter",
  "description": "QCubed application starter template",
  "keywords": ["qcubed", "framework", "project template"],
  "homepage": "http://qcu.be/",
  "type": "project",
  "license": "MIT",
  "support": {
    "issues": "https://github.com/qcubed/framework/issues?state=open",
    "source": "https://github.com/qcubed/framework"
  },
  "require": {
    "php": ">=5.4.0",
    "qcubed/framework": "dev-beta-3.0",
    "qcubed/composer": "dev-master",
    "qcubed/plugin_bootstrap": "^1.0",
    "twbs/bootstrap": "^3.3"
  },
  "require-dev": {
    "lastcraft/simpletest": "dev-master",
    "ezyang/htmlpurifier": "dev-master",
    "phpunit/phpunit": "4.8.*"
  },
  "autoload": {
      "psr-0": {
          "project": ""
      }
  },
  "minimum-stability":"dev",
  "config": {
      "preferred-install": "dist"
  }
}
`

**Comment by spekary** [comment]
OK. Try again.

**Comment by kpirbhai** [comment]
Still getting the exact same error.

**Comment by kpirbhai** [comment]
This isn't  new install. I had an error a couple of days ago that I don't exactly remember now but it had to do with the bootstrap plug and changing QControl in my project include files to extend from QCubed\Plugin\Bootstrap\Control. I simply changed it back to inherit from QBaseControl and composer worked. When running composer today it was obviously a different error but my QControl is extending the bootstrap control today while running composer update.

**Comment by spekary** [comment]
Change QControl back to inherit from QControlBase, run the composer update, then change QControl back to inherit from Bootstrap plugin and do it again. If still same error, tell me what is on that line.

**Comment by kpirbhai** [comment]
Yup. I changed my project/includes/controls/QControl.class.php to extend QControlBase and got no error.

**Comment by kpirbhai** [comment]
Still getting the error though when control inherits from bootstrap.

![image](https://cloud.githubusercontent.com/assets/5413608/15513199/4febadaa-21a9-11e6-9138-edee11f0a0f7.png)

**Comment by spekary** [comment]
Its installing an old version of the bootstrap plugin from a cache. (v1.0.1) It should be installing v1.0.2. Try changing to ^1.0.2 in composer.json on the plugin_bootstrap line.

**Comment by kpirbhai** [comment]
That did it. Composer ran with no errors while QControl extended Bootstrap.
I also ran my code again and everything is still working.
Thank you!
