### ISSUE TITLE
Bootsrap modal class needs to be done?

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_bootstrap#4]
This class is very much needed :)! Can we do it? See the link http://getbootstrap.com/javascript/#modals.

**Comment by spekary** [comment]
I have something that is the beginning. Bootstrap modals have a problem that they do not allow multiple modals at once. In other words, a modal cannot launch another modal. This is fixable by implementing a system that keeps track of the modals and stacks them using z-index setting, but that will take a little work.

**Comment by kukrik** [comment]
This question may be closed!
