### ISSUE TITLE
Class 'QCubed\\Plugin\\Bootstrap\\Control' not found

### ISSUE THREAD

**Issue by lucadambros** [qcubed/plugin_bootstrap#48]
Hi,
I'm having this problem:
`PHP Fatal error:  Class 'QCubed\\Plugin\\Bootstrap\\Control' not found in /var/www/html/project/includes/qcubed/controls/QControl.class.php on line 19
`
and I don't know why.

I followed the instruction but I noticed that the path of QControl.class.php (`project/includes/controls/QControl.class.php`) is different (mine is /var/www/html/project/includes/qcubed/controls/QControl.class.php) and when I try to modify from
`abstract class QControl extends QControlBase {`
to
`abstract class QControl extends QCubed\Plugin\Bootstrap\Control {`
I get the error.
Have I to change some file? Why in the apache2's log there are the double '\\'?

My configuration.inc.php is:
```

define ('__DOCROOT__', '/var/www/html');
define ('__VIRTUAL_DIRECTORY__', '');
define ('__SUBDIRECTORY__', '/project');
define('__VENDOR_ASSETS__', '/vendor');
define ('__BOOTSTRAP_CSS_', __DOCROOT__ . __SUBDIRECTORY__ . __VENDOR_ASSETS__.'/twbs/bootstrap/dist/css/bootstrap.css');
define ('__BOOTSTRAP_JS_', __DOCROOT__ . __SUBDIRECTORY__ . __VENDOR_ASSETS__. '/twbs/bootstrap/dist/js/bootstrap.css');
```
I'm using php5.5 and the last version of QCubed.
What I have to do?

**Edit:** I tried this:
```
require "/var/www/html/project/vendor/qcubed/plugin_bootstrap/includes/Control.php";
abstract class QControl extends QCubed\Plugin\Bootstrap\Control {
```
and the error changed into:

`PHP Fatal error:  Class QPanel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (QCubed\\Plugin\\Bootstrap\\Control::GetWrapperStyler) in /var/www/html/project/includes/qcubed/_core/base_controls/QPanel.class.php on line 7
`

**Comment by kukrik** [comment]
```
define ('__DOCROOT__', '/var/www/html');
define ('__VIRTUAL_DIRECTORY__', '');
define ('__SUBDIRECTORY__', '/project'); //What for? 
```
Please carefully read instructions of the configuration! Sometimes it may differ slightly depends on the server configuration.

```
require "/var/www/html/project/vendor/qcubed/plugin_bootstrap/includes/Control.php"; // It is not necessary
abstract class QControl extends QCubed\Plugin\Bootstrap\Control {
```
I do like that and it's not a problem for me.
```
// abstract class QControl extends QControlBase {
abstract class QControl extends QCubed\Plugin\Bootstrap\Control {
```
@spekary wrote well: 3. Point the base class to Bootstrap classes so that they add their functionality.
In your project/includes/controls/QControl.class.php file, have your QControl inherit from the base class. For example, you should change the first line to:

`abstract class QControl extends QCubed\Plugin\Bootstrap\Control {`

**Comment by lucadambros** [comment]
That's not what I asked. I tried following the instruction and I had the class not found error.
I tried other methods not written here but they didn't work.

**Comment by kukrik** [comment]
I'm sorry, when I realized wrong your question.

**Comment by spekary** [comment]
Whenever you get an error that a namespaced class cannot be found, the first place to look is the autoloader. The autoloader converts a namespaced name to an absolute path, and then does a require_once on that file.

We are currently relying on the composer autoloader to do this for us. So, either you did not install with composer, in which case you should do that. Or, the composer autoloader is not getting inserted into PHP, which is supposed to happen on this line in prepend.inc.php:
```
        if (file_exists (__QCUBED_CORE__ . '/../../../autoload.php')) {
            require __QCUBED_CORE__ . '/../../../autoload.php'; // Add the Composer autoloader if using Composer
        }
```
Some part of this process is broken. You could also just ```require_once('absolute path to bootstrap control file');```  at the top of your QControl.class.php file for now.

**Comment by spekary** [comment]
Also note I have just finished some major rework of this process for 4.0. The autoloader is now in a separate singleton service and much less likely to break by moving things around. In 4.0, the entire framework is dependent on the autoloader, since it is all namespaced.

**Comment by lucadambros** [comment]
I installed via Composer but in the prepend.inc.php there is nothing.
However my autoload file is in a different path anyway (it's in `project/vendor/autoload.php`)  and adding the right path in prepend.inc.php is not working (same error).
Where I can find the bootstrap control file?

**Comment by spekary** [comment]
It certainly sounds like your setup is very mixed up. If there is no autoload setup in prepend.inc.php, the autoloader will not work. Why its not there suggests you are not using version 3.x of qcubed, in which case none of this will work. Also, the project and vendor directories should be siblings.

The bootstrap control file should be in vendor/qcubed/plugin/bootstrap/includes.

**Comment by lucadambros** [comment]
I think you're right. I tried to require the Control file but it gave me this:
`PHP Fatal error: Class QPanel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (QCubed\\Plugin\\Bootstrap\\Control::GetWrapperStyler) in /var/www/html/project/includes/qcubed/_core/base_controls/QPanel.class.php on line 7`
I tried to install this plugin via composer and it's the first time I use it so maybe I don't have the right version of qcubed or the installation somehow failed. Is there other method for bootstrap in qcubed?
Thanks for the support.

**Comment by spekary** [comment]
The "_core" directory is version 2 only. You are mixing version 2 code with version 3 code, and that will not work. Version 3 is quite different in structure from version 2. Version 4 will also be a big departure in structure, but more in the underlying code. Hopefully version 4 is the last major rework, but I digress.

The best way forward for you is to start with version 3.0 I think, and start fresh. Follow the installation instructions to use composer to start with the app-starter. Once that is installed, edit your config files and do a codegen. Use the ModelEditor to make basic changes to your edit screens and list views, and then start copying from the old version to the new one. It may take some time, but in the end, your project will be better structured.

**Comment by lucadambros** [comment]
Thank you very much!
